### ISSUE TITLE
NOT APPLICABLE TO ALL WEBSITES

### ISSUE THREAD

**Issue by rajprakash00** [ashish493/Python_Scripts#1]
Hi @ashish493 ,
Here the script you have written is automated login script for your college wifi(to be specific for the hostel block wifi)
so i guess it's not for all websites.(as per you have written),e,g-gmail,facebook,etc.
Please see to this issue.

Regards,
raj

**Comment by ashish493** [comment]
Thanks @rajprakash00  for pulling the issue.
I, thereby, updated the code
